# The playground settings file allows for customization
# of setting for the tool.

# backends that are supported
backends: [docker, google, aws, podman]

# config editor
config_editor: vim

# Backend specific settings
default_backend: docker

# Don't try to look for best instance, just use instance types here
disable_cloud_select: false

google:
  zone: "us-central1-a"
  instance: "n2-standard-2"

aws:
  zone: "us-east-1"
  instance: "t2.medium"
