# The cloud cost estimator settings file allows for customization
# of setting for the estimator.

# backends that are supported
backends: [docker, google] #[aws, google, docker]

# config editor
config_editor: vim

# Backend specific settings
default_backend: docker

google:
  zone: "us-central1-a"
  instance: "n2-standard-2"

aws:
  zone: "us-east-1"
