name: deploy playground

on:
  # Always test on pull request
  pull_request: []

  # Deploy on merge to main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Container
    env:
      container: ghcr.io/converged-computing/playground
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Space For Build
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - name: Build and Tag Container
        run: |
            docker build -t ${{ env.container }} .
            set -x
            version=$(docker run -i --entrypoint playground ${{ env.container }} version)
            printf "Found version ${version}\n"
            docker tag ${{ env.container }}:latest ${{ env.container }}:${version}

      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        run: |
            set -x
            docker images
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker push --all-tags ${{ env.container }}
